export { default as RecentFavorites } from './Favorites/RecentFavorites';
export { default as GenrePage } from './Genre/GenrePage';
export { default as Home } from './Home';
export { default as Pagination } from './Home/components/Pagination';
export { default as MovieAll } from './Movies/MovieAll';
export { default as MoviePage } from './Movies/MoviePage';
export { default as MovieDescriptionCard } from './Movies/components/MovieDescriptionCard';
export { default as MovieEmbedServers } from './Movies/components/MovieEmbedServers';
export { default as MoviePlayer } from './Movies/components/MoviePlayer';
export { default as SearchAll } from './Search/SearchAll';
export { default as SeriesAll } from './Series/SeriesAll';
export { default as SeriesPage } from './Series/SeriesPage';
export { default as SeriesCard } from './Series/components/SeriesCard';
export * from './index';
